# Generated by Django 5.0.2 on 2024-02-15 07:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.FileField(blank=True, null=True, upload_to='hospital_reports/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('Patients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.department')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.hospitaldetails')),
            ],
            options={
                'db_table': 'lab_reports_hospital',
                'managed': True,
            },
        ),
    ]
