# Generated by Django 5.0.2 on 2024-02-20 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_labreports'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labreports',
            name='Patients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
    ]
