# Generated by Django 5.0.2 on 2024-02-20 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_alter_labreports_patients'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreports',
            name='report_name',
            field=models.CharField(default='pop', max_length=200),
            preserve_default=False,
        ),
    ]
