# Generated by Django 5.0.2 on 2024-02-20 04:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_labreports_report_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreports',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
