# Generated by Django 5.0.2 on 2024-03-13 21:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0005_labreports_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitaladmin',
            name='user',
        ),
        migrations.AddField(
            model_name='hospitaladmin',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='hospitaladmin',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitals.hospitaladmin'),
        ),
        migrations.AddField(
            model_name='hospitaladmin',
            name='name',
            field=models.CharField(default='sd', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitaladmin',
            name='password',
            field=models.CharField(default='sd', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitaladmin',
            name='username',
            field=models.CharField(default='ds', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
