# Generated by Django 5.0.2 on 2024-03-13 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0006_remove_hospitaladmin_user_hospitaladmin_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitaladmin',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitals.hospitaldetails'),
        ),
    ]
