# Generated by Django 5.0.2 on 2024-04-15 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0008_medicinesname'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferToDoctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.hospitaldetails')),
            ],
            options={
                'db_table': 'refer_to',
                'managed': True,
            },
        ),
    ]
