# Generated by Django 5.0.2 on 2024-04-30 04:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0009_refertodoctors'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaldetails',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
