# Generated by Django 5.0.2 on 2024-05-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0010_hospitaldetails_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaldetails',
            name='hospital_image',
            field=models.ImageField(blank=True, null=True, upload_to='hospital_images/'),
        ),
    ]
