# Generated by Django 5.0.2 on 2024-05-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0011_hospitaldetails_hospital_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaldetails',
            name='google_link',
            field=models.TextField(blank=True),
        ),
    ]
