# Generated by Django 5.0.2 on 2024-05-25 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0013_alter_department_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinesname',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
