# Generated by Django 5.0.2 on 2024-05-28 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0015_hospitaladmin_ujur_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitaladmin',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_details_account', to='hospitals.hospitaldetails'),
        ),
    ]
