# Generated by Django 5.0.2 on 2024-06-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0016_alter_hospitaladmin_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaldetails',
            name='years_of_establishment',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
