"""
Django settings for ujurbackend project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%&fe-lx@nx@r=kpipq0w!tficd_fk6dl@6x#oa*8%92ts0@vq+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '91.108.110.30',
    '192.168.29.217',
    "*",
    '0.0.0.0',
    '10.123.0.63'
]
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True

# Application definition
jwt_secret_key = 'secretKeyRight34'
recovery_code = "X5RGYQ353MMZBN5J5P1S8QS3"

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'users',
    'patients',
    'doctors',
    'hospitals',
    "admin_hospital"

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ujurbackend.urls'

CORS_ALLOWED_ORIGINS = [
            'http://0.0.0.0',

    'https://91.108.110.30',
        'http://91.108.110.30',

    'http://localhost:3000',

'http://localhost:3001',
'http://127.0.0.1:3000',
'http://91.108.110.87:3000',
'http://91.108.110.87:3001',
'http://91.108.110.87:3002',
        "http://localhost",

"http://91.108.110.30:3000",
"http://192.168.29.217:3000"
]


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files (User uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ujurbackend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

CSRF_TRUSTED_ORIGINS = [  "http://192.168.29.217", "http://0.0.0.0", "http://91.108.110.87"," http://localhost", 'http://localhost:3000', 'http://localhost:3001', "http://127.0.0.1:3000", 'http://91.108.110.87:3000',
'http://91.108.110.87:3001',
'http://91.108.110.87:3002',
"http://91.108.110.30:3000",
"http://192.168.29.217:3000"

]
CORS_ORIGIN_WHITELIST = [  "http://192.168.29.217", "http://0.0.0.0", "http://91.108.110.87", " http://localhost", 'http://localhost:3000', 'http://localhost:3001', "http://127.0.0.1:3000", 'http://91.108.110.87:3000',
'http://91.108.110.87:3001',
'http://91.108.110.87:3002',
"http://91.108.110.30:3000",
"http://192.168.29.217:3000"

]
# CORS_ORIGIN_WHITELIST = [" http://localhost", "http://127.0.0.1", "http://localhost",'http://localhost:3000', 'http://localhost:3001' ,  "http://127.0.0.1:3000", 'http://91.108.110.87:3000',
# 'http://91.108.110.87:3001',
# 'http://91.108.110.87:3002',
# "http://91.108.110.30:3000",
#                          "http://192.168.29.217:3000"
# ]


STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'jwtToken'
]
RAZOR_KEY_ID = "rzp_live_6Q4vEajbmruIsE"
RAZOR_KEY_SECRET = "42WmwU9s6qHjzDvAQymvHDlL"