# Generated by Django 5.0.2 on 2024-02-12 04:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('specialization', models.CharField(max_length=100)),
                ('experience', models.PositiveIntegerField()),
                ('education', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='doctor_profiles/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='doctor_sign/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'doctor_details',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='doctorSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morning_timings', models.CharField(max_length=200)),
                ('afternoon_timings', models.CharField(max_length=200)),
                ('evening_timings', models.CharField(max_length=200)),
                ('morning_slots', models.PositiveIntegerField()),
                ('afternoon_slots', models.PositiveIntegerField()),
                ('evening_slots', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'doctor_slots',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_booked', models.DateTimeField()),
                ('date_appointment', models.DateTimeField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='patients.patient')),
            ],
            options={
                'db_table': 'appointment',
                'managed': True,
            },
        ),
    ]
