# Generated by Django 5.0.2 on 2024-02-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_favdoctors_patientdoctorreviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordetails',
            name='full_name',
            field=models.CharField(default='yatin vohra', max_length=100),
            preserve_default=False,
        ),
    ]
