# Generated by Django 5.0.2 on 2024-02-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_doctordetails_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorslots',
            name='afternoon_slots_price',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='doctorslots',
            name='evening_slots_price',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='doctorslots',
            name='morning_slots_price',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='doctorslots',
            name='afternoon_slots',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='doctorslots',
            name='evening_slots',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='doctorslots',
            name='morning_slots',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
