# Generated by Django 5.0.2 on 2024-02-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_alter_doctorslots_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_mode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='created', max_length=100),
        ),
    ]
