# Generated by Django 5.0.2 on 2024-02-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_appointment_payment_mode_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordetails',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctordetails',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
