# Generated by Django 5.0.2 on 2024-03-02 11:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0009_doctordetails_email_doctordetails_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdoctorreviews',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
