# Generated by Django 5.0.2 on 2024-03-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0010_patientdoctorreviews_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdoctorreviews',
            name='comment',
            field=models.TextField(default='You are very good, Doctors are very good'),
            preserve_default=False,
        ),
    ]
