# Generated by Django 5.0.2 on 2024-03-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0011_patientdoctorreviews_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor_instruction',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patients_query',
            field=models.TextField(null=True),
        ),
    ]
