# Generated by Django 5.0.2 on 2024-03-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0013_alter_appointment_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorslots',
            name='medical_license',
            field=models.CharField(default='NS09SNMS803IKS', max_length=200),
            preserve_default=False,
        ),
    ]
