# Generated by Django 5.0.2 on 2024-03-04 02:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0015_appointment_pdf_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('status', models.CharField(max_length=200, null=True)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'doctor_leave',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='doctordetails',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
