# Generated by Django 5.0.2 on 2024-03-18 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0018_doctorleave_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPasswordRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('status', models.CharField(default='REQUESTED', max_length=200, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_password_doctor', to='doctors.doctordetails')),
            ],
            options={
                'db_table': 'reset_password',
                'managed': True,
            },
        ),
    ]
