# Generated by Django 5.0.2 on 2024-04-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0019_resetpasswordrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_slot',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
