# Generated by Django 5.0.2 on 2024-04-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0020_appointment_appointment_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_slot',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
