# Generated by Django 5.0.2 on 2024-04-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0021_alter_appointment_appointment_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_documents',
            field=models.FileField(blank=True, null=True, upload_to='patient_documents/'),
        ),
    ]
