# Generated by Django 5.0.2 on 2024-04-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0022_appointment_patient_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorleave',
            name='status',
            field=models.CharField(default='Waiting for approval', max_length=200, null=True),
        ),
    ]
