# Generated by Django 5.0.2 on 2024-05-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0023_alter_doctorleave_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordetails',
            name='bio',
            field=models.TextField(null=True),
        ),
    ]
