# Generated by Django 5.0.2 on 2024-05-15 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0024_alter_doctordetails_bio'),
        ('hospitals', '0012_hospitaldetails_google_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordetails',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='doctordetails',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitals.department'),
        ),
        migrations.AlterField(
            model_name='doctordetails',
            name='education',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='doctordetails',
            name='specialization',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
