# Generated by Django 5.0.2 on 2024-05-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0026_alter_doctorslots_afternoon_timings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorslots',
            name='medical_license',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
