# Generated by Django 5.0.2 on 2024-05-17 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0027_alter_doctorslots_medical_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='lab_report',
            field=models.FileField(blank=True, null=True, upload_to='lab_report/'),
        ),
    ]
