# Generated by Django 5.0.2 on 2024-05-18 16:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0028_appointment_lab_report'),
        ('hospitals', '0012_hospitaldetails_google_link'),
        ('patients', '0008_patient_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalPatientReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviews_star', models.IntegerField(null=True)),
                ('comment', models.TextField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_reviews_hospital', to='hospitals.hospitaldetails')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_reviews_hospital', to='patients.patient')),
            ],
            options={
                'db_table': 'hospital_doctor_reviews',
                'managed': True,
            },
        ),
    ]
