# Generated by Django 5.0.2 on 2024-05-18 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0029_hospitalpatientreviews'),
        ('hospitals', '0012_hospitaldetails_google_link'),
        ('patients', '0008_patient_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalpatientreviews',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_reviews', to='hospitals.hospitaldetails'),
        ),
        migrations.AlterField(
            model_name='hospitalpatientreviews',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_hospital', to='patients.patient'),
        ),
    ]
