# Generated by Django 5.0.2 on 2024-05-18 16:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0030_alter_hospitalpatientreviews_hospital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalpatientreviews',
            name='created_at2',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
