# Generated by Django 5.0.2 on 2024-05-18 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0031_hospitalpatientreviews_created_at2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalpatientreviews',
            name='created_at2',
        ),
    ]
