# Generated by Django 5.0.2 on 2024-05-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0032_remove_hospitalpatientreviews_created_at2'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordetails',
            name='ujur_id',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
