# Generated by Django 5.0.2 on 2024-06-02 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0033_doctordetails_ujur_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdoctorreviews',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 8, 35, 27, 569155)),
        ),
    ]
