# Generated by Django 5.0.2 on 2024-06-02 08:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0034_alter_patientdoctorreviews_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdoctorreviews',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
