# Generated by Django 5.0.2 on 2024-06-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0035_alter_patientdoctorreviews_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
