# Generated by Django 5.0.2 on 2024-06-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0040_remove_revenue_doctor_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='doctor_fees',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
