# Generated by Django 5.0.2 on 2024-06-29 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0042_appointment_razorpay_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdoctorreviews',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
