# Generated by Django 5.0.2 on 2024-08-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0045_doctordetails_prescription_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='prescription_method',
            field=models.CharField(default='digital', max_length=100),
        ),
    ]
