# Generated by Django 5.0.2 on 2024-08-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0046_appointment_prescription_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='getChiefQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('value', models.TextField()),
            ],
            options={
                'db_table': 'get_chief_query',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='labTests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('value', models.TextField()),
            ],
            options={
                'db_table': 'lab_tests',
                'managed': True,
            },
        ),
    ]
