# Generated by Django 5.0.2 on 2024-08-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0047_getchiefquery_labtests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getchiefquery',
            name='name',
        ),
        migrations.AddField(
            model_name='getchiefquery',
            name='label',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='getchiefquery',
            name='value',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
