# Generated by Django 5.0.2 on 2024-08-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0048_remove_getchiefquery_name_getchiefquery_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtests',
            name='name',
        ),
        migrations.AddField(
            model_name='labtests',
            name='label',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='labtests',
            name='value',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
