# Generated by Django 5.0.2 on 2024-08-20 11:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0049_remove_labtests_name_labtests_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='getchiefquery',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='labtests',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
