# Generated by Django 5.0.2 on 2024-02-22 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='district',
            field=models.CharField(default='delhi', max_length=100),
            preserve_default=False,
        ),
    ]
