# Generated by Django 5.0.2 on 2024-04-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_patient_blood_group_alter_patient_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='block',
            field=models.CharField(default=5.8, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='height',
            field=models.DecimalField(decimal_places=2, help_text='Weight in Foots', max_digits=5, null=True),
        ),
    ]
