# Generated by Django 5.0.2 on 2024-04-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_patient_block_patient_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='ujur_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
